-- ====================================================================
-- lost2found • Complete Supabase Database Schema & RLS Security Policies
-- Project URL: https://gdngcjfgajkjdjosgtlc.supabase.co
-- ====================================================================

-- 1. PROFILES TABLE (Linked to Supabase Auth)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'user', -- 'user' | 'admin'
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone" 
ON public.profiles FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile" 
ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update their own profile" 
ON public.profiles FOR UPDATE USING (auth.uid() = id);


-- 2. LOST AND FOUND ITEMS TABLE
CREATE TABLE IF NOT EXISTS public.items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('lost', 'found')),
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  color TEXT,
  brand TEXT,
  location TEXT NOT NULL,
  date TEXT NOT NULL,
  image_url TEXT,
  secret_detail TEXT, -- Hidden private verification detail
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'claimed', 'returned')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;

-- Items Policies
CREATE POLICY "Anyone can view open/claimed/returned items" 
ON public.items FOR SELECT USING (true);

CREATE POLICY "Authenticated users can create items" 
ON public.items FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own items" 
ON public.items FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own items" 
ON public.items FOR DELETE USING (auth.uid() = user_id);


-- 3. NOTIFICATIONS TABLE
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL, -- Owner receiving the notice
  item_id BIGINT REFERENCES public.items(id) ON DELETE CASCADE,
  finder_name TEXT,
  message TEXT NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Notifications Policies
CREATE POLICY "Users can view only their own notifications" 
ON public.notifications FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Authenticated users can send notifications to item owners" 
ON public.notifications FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Users can mark their own notifications as read" 
ON public.notifications FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own notifications" 
ON public.notifications FOR DELETE USING (auth.uid() = user_id);


-- 4. FEEDBACK / REUNITED STORIES TABLE
CREATE TABLE IF NOT EXISTS public.feedbacks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  user_name TEXT NOT NULL,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.feedbacks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read feedbacks / reunited stories" 
ON public.feedbacks FOR SELECT USING (true);

CREATE POLICY "Authenticated users can submit feedback" 
ON public.feedbacks FOR INSERT WITH CHECK (auth.role() = 'authenticated');


-- 5. STORAGE BUCKET FOR ITEM IMAGES
-- (Run this in the Supabase SQL editor to create the public bucket and policies)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('item-images', 'item-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Storage Policies
CREATE POLICY "Public Access: Item images are viewable by everyone" 
ON storage.objects FOR SELECT USING (bucket_id = 'item-images');

CREATE POLICY "Authenticated users can upload item images" 
ON storage.objects FOR INSERT WITH CHECK (
  bucket_id = 'item-images' AND auth.role() = 'authenticated'
);

CREATE POLICY "Users can update own uploaded images" 
ON storage.objects FOR UPDATE USING (
  bucket_id = 'item-images' AND auth.uid() = owner
);

CREATE POLICY "Users can delete own uploaded images" 
ON storage.objects FOR DELETE USING (
  bucket_id = 'item-images' AND auth.uid() = owner
);


-- 6. AUTOMATIC PROFILE CREATION TRIGGER (Optional Convenience)
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email, role)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    new.email,
    'user'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
